carts/urls.py
from django.conf.urls import url

from .views import ( 
	cart_home, 
	cart_update,
	checkout_home,
	checkout_complete_view
	)
	

urlpatterns = [
	url(r'^$', cart_home, name='home'),
	url(r'^update/$', cart_update, name='update'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^checkout/success/$', checkout_complete_view, name='success'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


from accounts.views import  LoginView, RegisterView, guest_register_view
from .views import home_page, contact_page, about_page
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from carts.views import cart_home, cart_detail_api_view
from billing.views import payment_method_view
	

urlpatterns = [
	url(r'^$', home_page, name='home'),
	url(r'^login/', LoginView.as_view(), name='login'),
	url(r'^logout/', LogoutView.as_view(), name='logout'),
	url(r'^register/guest', guest_register_view, name='guest_register_view'),
	url(r'^register/', RegisterView.as_view(), name='register'),
	url(r'^checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
	url(r'^checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
	url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
	url(r'^contact/', contact_page, name='contact'),
	url(r'^about/', about_page, name='about'),
	url(r'^api/cart/', cart_detail_api_view, name='api-cart'),
	url(r'^products/', include("products.urls", namespace='products')),
	url(r'^search/', include("search.urls", namespace='search')),
	url(r'^cart/', include("carts.urls", namespace='cart')),
	url(r'^billing/payment-method/', payment_method_view, name='billing-payment-method'),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import ( 
	ProductListView, 
	ProductDetailSlugView
	)
	

urlpatterns = [
	url(r'^$', ProductListView.as_view(), name='list'),
	url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail')
]

templates/base/css.html
  {% load static %}  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

      <link rel='stylesheet' href="{% static 'css/stripe-cutom-style.css' %}" />

templates/base/js.html
     {% load static %}  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  

    <script src='{% static "js/ecommerce.js" %}'></script>
    <script src='{% static "js/csrf.ajax.js" %}'></script>

    <!--stripe js -->
    <script src="https://js.stripe.com/v3/"></script>

templates/base/nav.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'products:list' as product_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-2">
	<div class='container'>
	  <a class="navbar-brand" href="#">{% if brand_name %} {{ brand_name }} {% else %}Toxic{% endif %}</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapseLinks"  aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarCollapseLinks">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
	        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
	        <a class="nav-link" href="{{ contact_url }}">Contact</a>
	      </li>
	      <li class="nav-item {% if request.path == about_url %} active {% endif %}">
	        <a class="nav-link" href="{{ about_url }}">About us </a>
	      </li>
	      <li class="nav-item {% if request.path == product_url %} active {% endif %}">
	        <a class="nav-link" href="{{ product_url }}">Products</a>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
	        <a class="nav-link" href="{{ logout_url }}">Log Out</a>
	      </li>
	      {% else %}
	      <li class="nav-item {% if request.path == login_url %} active {% endif %}">
	        <a class="nav-link" href="{{ login_url }}">Login</a>
	      </li>
	      <li class="nav-item {% if request.path == register_url %} active {% endif %}">
	        <a class="nav-link" href="{{ register_url }}">Register</a>
	      </li>
	      {% endif %}
	      <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
	        <a class="nav-link" href="{{ cart_url }}"><span class='navbar_cart_count'>{{ request.session.cart_item }}</span> <i class="fa 
	        fa-shopping-cart" aria-hidden="true"></i></a>
	      </li>
	    </ul>

	    {% include "search/snippets/search-form.html" %}
	    
	  </div>
	</div>
</nav>
<!-- <i class="fas fa-shopping-cart"></i>
<i class="fas fa-cart-arrow-down"></i>
 -->
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">{% if brand_name %} {{ brand_name }} {% else %}Toxic{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'products:list' %}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
	<form class="form-inline my-2 my-lg-0">
	  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	</form>
  </div>
</nav> -->